name: sudevdas
favicon: null
layout_spectrum: 0.62139
typography_spectrum: 0.22266263654455543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8125
  lightness: 0.3554099122993648
  saturation: 0.18279006821103394
  rhythmicContrast: 0.7119527331087738
purpose: []
